export default {
  content: [
    "./index.html",
    "./seller.html",
    "./admin.html",
    "./src/**/*.{js,jsx,ts,tsx}",
  ],
  theme: {
    extend: {
      colors: {
// ─── Public App — OPTION 1 ACTIVE: "Kisan Gold" ──────
        // 'pub-primary':              '#2D7A3E',
        // 'pub-primary-dark':         '#1F5C2D',
        // 'pub-primary-light':        '#EEF7EE',
        // 'pub-accent':               '#D97706',
        // 'pub-accent-dark':          '#B45309',
        // 'pub-accent-light':         '#FEF3C7',
        // 'pub-page-bg':              '#FAF8F4',
        // 'pub-section-1':            '#FFFFFF',
        // 'pub-section-2':            '#F2F7F2',
        // 'pub-section-2-border':     '#D4E8D4',
        // 'pub-section-3':            '#FDF6EC',
        // 'pub-section-3-border':     '#EDD9B0',
        // 'pub-header':               '#1B5E2F',
        // 'pub-header-dark':          '#14451F',
        // 'pub-header-mid':           '#1F6B35',
        // 'pub-header-bottom':        '#111D2E',
        // 'pub-header-nav-hover':     '#A7F3C0',

        // ── OPTION 2: "Mitti" ──────────────────────────────
        // 'pub-primary':              '#3B6E2F',
        // 'pub-primary-dark':         '#2A5020',
        // 'pub-primary-light':        '#EAF2E8',
        // 'pub-accent':               '#C2410C',
        // 'pub-accent-dark':          '#9A3412',
        // 'pub-accent-light':         '#FFEDD5',
        // 'pub-page-bg':              '#FDF8F3',
        // 'pub-section-1':            '#FFFFFF',
        // 'pub-section-2':            '#F5EDE0',
        // 'pub-section-2-border':     '#E8D5BC',
        // 'pub-section-3':            '#FEF3E8',
        // 'pub-section-3-border':     '#F5CBA7',
        // 'pub-header':               '#3B2A1A',
        // 'pub-header-dark':          '#2C1E10',
        // 'pub-header-mid':           '#4A3525',
        // 'pub-header-bottom':        '#1C1210',
        // 'pub-header-nav-hover':     '#F5CBA7',

        // ── OPTION 3: "Fresh Market" ───────────────────────
        // 'pub-primary':              '#16A34A',
        // 'pub-primary-dark':         '#15803D',
        // 'pub-primary-light':        '#DCFCE7',
        // 'pub-accent':               '#0284C7',
        // 'pub-accent-dark':          '#0369A1',
        // 'pub-accent-light':         '#E0F2FE',
        // 'pub-page-bg':              '#F0F9FF',
        // 'pub-section-1':            '#FFFFFF',
        // 'pub-section-2':            '#ECFDF5',
        // 'pub-section-2-border':     '#A7F3D0',
        // 'pub-section-3':            '#F0F9FF',
        // 'pub-section-3-border':     '#BAE6FD',
        // 'pub-header':               '#0C4A6E',
        // 'pub-header-dark':          '#083350',
        // 'pub-header-mid':           '#0E5F8A',
        // 'pub-header-bottom':        '#061E30',
        // 'pub-header-nav-hover':     '#BAE6FD',

        // ── OPTION 4: "Night Harvest" ──────────────────────
        // 'pub-primary':              '#22C55E',
        // 'pub-primary-dark':         '#16A34A',
        // 'pub-primary-light':        '#DCFCE7',
        // 'pub-accent':               '#FBBF24',
        // 'pub-accent-dark':          '#F59E0B',
        // 'pub-accent-light':         '#FEF9C3',
        // 'pub-page-bg':              '#F1F5F1',
        // 'pub-section-1':            '#FFFFFF',
        // 'pub-section-2':            '#E8F5E9',
        // 'pub-section-2-border':     '#C6E8C6',
        // 'pub-section-3':            '#FEFCE8',
        // 'pub-section-3-border':     '#FDE68A',
        // 'pub-header':               '#052E16',
        // 'pub-header-dark':          '#021C0E',
        // 'pub-header-mid':           '#083D1E',
        // 'pub-header-bottom':        '#021C0E',
        // 'pub-header-nav-hover':     '#86EFAC',

        // ── OPTION 5: "Sona Mitti" ─────────────────────────
        'pub-primary':              '#2D7A3E',
        'pub-primary-dark':         '#1F5C2D',
        'pub-primary-light':        '#EEF7EE',
        'pub-accent':               '#E65C00',
        'pub-accent-dark':          '#C24B00',
        'pub-accent-light':         '#FFF0E0',
        'pub-page-bg':              '#FFFFFF',
        'pub-section-1':            '#FFFFFF',
        'pub-section-2':            '#EEF6FF',
        'pub-section-2-border':     '#BDD9F7',
        'pub-section-3':            '#FFF8EC',
        'pub-section-3-border':     '#FFD98E',
        'pub-header':               '#1A3C1F',
        'pub-header-dark':          '#112815',
        'pub-header-mid':           '#1F4A25',
        'pub-header-bottom':        '#0D1A0F',
        'pub-header-nav-hover':     '#FFD580',


        // ─── Seller App ───────────────────────────
        'sel-primary':       '#1E40AF',
        'sel-primary-dark':  '#1E3A8A',
        'sel-accent':        '#F59E0B',
        'sel-header':        '#1E293B',

        // ─── Admin App ────────────────────────────
        'adm-primary':       '#7C3AED',
        'adm-primary-dark':  '#6D28D9',
        'adm-accent':        '#EF4444',
        'adm-header':        '#1F2937',
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', 'sans-serif'],
      },
      boxShadow: {
        'card':       '0 1px 3px rgba(0,0,0,0.08), 0 1px 2px rgba(0,0,0,0.04)',
        'card-hover': '0 4px 12px rgba(0,0,0,0.12)',
        'header':     '0 2px 12px rgba(0,0,0,0.15)',
      },
    },
  },
  safelist: [
    'bg-pub-section-1',
    'bg-pub-section-2',
    'bg-pub-section-3',
    'border-pub-section-2-border',
    'border-pub-section-3-border',
  ],
  plugins: [],
}